#!/bin/bash

DATE=`date +%Y-%m-%d`
echo $DATE

../bin/console addons:github:sync all
../bin/console addons:github:sync:files all
../bin/console addons:github:sync:releases all
../bin/console addons:content:generate
../bin/console addons:composer:sync
../bin/console addons:composer:collect
../bin/console addons:bower:sync
