#!/bin/bash

DATE=`date +%Y-%m-%d`
echo $DATE

../bin/console app:addons:sync:github all
../bin/console app:addons:sync:github-files all
../bin/console app:addons:generate:content
../bin/console app:addons:sync:composer
../bin/console app:addons:sync:bower
../bin/console app:addons:composer:collect
