#!/bin/bash

DATE=`date +%Y-%m-%d`
echo $DATE

../bin/console app:addons:sync:github all --rest
../bin/console app:addons:sync:github-files all --rest
../bin/console app:addons:content:generate --rest
